/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles.Nivel0;

/**
 *
 * @author EQUINOX
 */
public class PanelDepartamentos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDepartamentos
     */
    public PanelDepartamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cajaCodigoPD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaNombrePD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBBuscar = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel6.setText("DEPARTAMENTOS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 130, 27));

        cajaCodigoPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodigoPDActionPerformed(evt);
            }
        });
        add(cajaCodigoPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 150, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel7.setText("NOMBRE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 31));

        cajaNombrePD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombrePDActionPerformed(evt);
            }
        });
        add(cajaNombrePD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel8.setText("CODIGO:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 31));

        JBBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBBuscar.setText("Buscar");
        add(JBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        JBSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBSalir.setText("Salir");
        add(JBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cajaCodigoPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodigoPDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCodigoPDActionPerformed

    private void cajaNombrePDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombrePDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombrePDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JTextField cajaCodigoPD;
    private javax.swing.JTextField cajaNombrePD;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
